{% set name = "pystemmer" %}
{% set version = "2.2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyStemmer-{{ version }}.tar.gz
  sha256: 9f3b366f1ed06b49dc1868bf0aefd884423db80f3431be442d0f993e448cc67b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython >=0.28.5,<1.0
    - setuptools >=18.0
    - pip
  run:
    - python

test:
  imports:
    - Stemmer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snowballstem/pystemmer/
  summary: Snowball stemming algorithms, for information retrieval
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - libstemmer_c-2.2.0/COPYING

extra:
  recipe-maintainers:
    - thewchan
